### ISSUE TITLE
need author access

### ISSUE THREAD

**Issue by tusharnankani** [mihikagaonkar/OTC-Dashboard#1]
I logged in, then I signed up for Power BI. 
Then, it shows: 

![image](https://user-images.githubusercontent.com/61280281/152856709-c33ae99f-0ff9-4403-a1aa-4da1deee85e2.png)

**Comment by tusharnankani** [comment]
My bad, this worked out. 
The trial started

![image](https://user-images.githubusercontent.com/61280281/152856846-4c5039be-008b-4119-a6e8-6f868edcf4e5.png)

But does that mean, after 60 days, I won't be able to access the dashboard?

**Comment by mihikagaonkar** [comment]
Were you able to access the report after you got the trial?

**Comment by tusharnankani** [comment]
Yes. 

![image](https://user-images.githubusercontent.com/61280281/152860749-3fb99445-f159-4d80-9605-3c1f479e9dc1.png)

**Comment by mihikagaonkar** [comment]
I am trying to work out how to publish it publicly.
