### ISSUE TITLE
docs: sort/arrange directories 

### ISSUE THREAD

**Issue by tusharnankani** [mihikagaonkar/OTC-Dashboard#2]
While I was going through the code, the helper files, the notebooks, the data felt a bit scattered.

![image](https://user-images.githubusercontent.com/61280281/152857902-8a0f0044-6b72-4c61-bf01-b2012964f7c9.png)

Suggestion:

You can create proper directories for all your files, then document them to explain your thought process around them.

Eg: 

```
*
└───data
    ├───summaries
        └───*.md
    └───.*csv
└───util
    └───helper_file.ipynb
└───assets
```

Further, you can write your workflow. Which helper file you used, then where did you use that output in another helper file, so on and so forth? 
Just a suggestion.

Really great project! So proud <3

**Comment by mihikagaonkar** [comment]
Thank you Tushar!

**Comment by tusharnankani** [comment]
Love the changes. Looks clean, nice work :D

**Comment by tusharnankani** [comment]
Here's a nice article around it: [Colocation](https://kentcdodds.com/blog/colocation)
